language: node_js
node_js: "10.15.0"
cache:
  directories:
    - "node_modules"
  yarn: true
services:
  - postgresql
before_install:
- npm update
install:
- npm install
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - PGPORT=5433
before_script:
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER favour WITH PASSWORD 'password1';" -U postgres
  - npm run test-migrate:refresh
  - npm run test:seed
script:
- npm test
after_success:
- npm run coverage