language: node_js
node_js: "10.15.0"
cache:
  directories:
    - "node_modules"
services:
 - postgresql
  yarn: true
before_install:
- npm update
before_script:
 - psql -c 'create database questioner_test_db;' -U postgres
 - npm run test-migrate:refresh
install:
- npm install
script:
- npm test
- npm run coverage