language: node_js
node_js: "10.15.0"
cache:
  directories:
    - "node_modules"
  yarn: true
services:
  - postgresql
before_install:
- npm update
install:
- npm install
before_script:
  - psql -c 'create database testdb;' -U postgres
script:
- npm test
after_success:
- npm run coverage