language: node_js
node_js: "10.15.0"
env:
  global:
    - CC_TEST_REPORTER_ID=c560bd54d67c159300a5b47efcb94068f3e7ba16d48961831c3c445def457636
cache:
  directories:
    - "node_modules"
  yarn: true
services:
  - postgresql
before_install:
- npm update
install:
- npm install
before_script:
  - psql -c "CREATE USER favour WITH PASSWORD 'password1';"
  - psql -c 'create database testdb;'
  - npm run test-migrate:refresh
  - npm run build
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- npm run travis-test
after_success:
- npm run coverage
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT